openapi: 3.0.0
info:
  title: API de Categorias
  version: 1.0.0
  description: API para gerenciamento de categorias

paths:
  /categoria:
    post:
      summary: Cria uma nova categoria
      tags:
        - Categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Tecnologia"
                status:
                  type: string
                  enum:
                    - "ATIVO"
                    - "INATIVO"
                  example: "ATIVO"
                idPai:
                  type: integer
                  nullable: true
                  example: null
        required: true
      responses:
        "200":
          description: Categoria criada com sucesso
        "400":
          description: Dados inválidos
        "500":
          description: Erro interno
    get:
      summary: Busca categorias com filtros
      tags:
        - Categoria
      parameters:
        - description: Filtros para busca
          in: query
          name: where
          schema:
            example: '{"search": {"id": "1", "idPai": "1"}, "operator": "OR"}'
            type: string
        - description: Filtros com busca aproximada
          in: query
          name: whereLike
          schema:
            example: '{"search": {"nome":"Tec", "nivel": "1"}, "operator": "OR"}'
            type: string
        - description: Ordenação dos resultados
          in: query
          name: order
          schema:
            example: '[["id", "DESC"]]'
            type: string
        - description: Limite de resultados por página
          in: query
          name: limit
          schema:
            example: 10
            type: integer
        - description: Página atual para paginação
          in: query
          name: page
          schema:
            example: 1
            type: integer
        - description: Colunas a serem retornadas na busca
          in: query
          name: attributes
          schema:
            example: '["id", "nome", "status"]'
            type: string
        - description: Busca o range
          in: query
          name: whereBetween
          schema:
            example: '{"createdAt":["2024-11-13 03:00:00","2024-11-13 02:59:59"]}'
            type: string
      responses:
        "200":
          description: Busca realizada com sucesso
        "500":
          description: Erro interno
  /categoria/{id}:
    put:
      summary: Atualiza uma categoria existente
      tags:
        - Categoria
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da categoria a ser atualizada
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                  example: "Tecnologia Avançada"
                status:
                  type: string
                  enum:
                    - "ATIVO"
                    - "INATIVO"
                  example: "ATIVO"
        required: true
      responses:
        "200":
          description: Categoria atualizada com sucesso
        "404":
          description: Categoria não encontrada
        "500":
          description: Erro interno
    delete:
      summary: Deleta uma categoria existente
      tags:
        - Categoria
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID da categoria a ser deletada
      responses:
        "200":
          description: Categoria deletada com sucesso
        "404":
          description: Categoria não encontrada
        "500":
          description: Erro interno

tags:
  - name: Categoria
    description: Operações relacionadas a categorias
